"""
The column names may be too long to print.
Here we define a mapping from pandas DataFrame columns to shorter column names.
"""

mapping = {
    'POSIX_BYTES_READ_PERC'           : "Bytes read %", 
    'POSIX_BYTES_WRITTEN_PERC'        : "Bytes written %",
    'POSIX_unique_bytes_perc'         : "Unique file\nbytes %",
    'POSIX_shared_bytes_perc'         : "Shared file\nbytes %",
    'POSIX_read_only_bytes_perc'      : "RO bytes %",
    'POSIX_read_write_bytes_perc'     : "R/W bytes %",
    'POSIX_write_only_bytes_perc'     : "WO bytes %",
    'POSIX_unique_files_perc'         : "% files\nunique",
    'POSIX_shared_files_perc'         : "% files\nshared",
    'POSIX_read_only_files_perc'      : "RO file %",
    'POSIX_read_write_files_perc'     : "R/W file %",
    'POSIX_write_only_files_perc'     : "WO file%",
    'POSIX_READS_PERC'                : "Read ops %",
    'POSIX_WRITES_PERC'               : "Write ops %",
    'POSIX_RW_SWITCHES_PERC'          : "% R/W\nswitches",
    'POSIX_SEQ_READS_PERC'            : "% R Ops\nsequential",
    'POSIX_SEQ_WRITES_PERC'           : "% R Ops\nsequential",
    'POSIX_CONSEC_READS_PERC'         : "% R Ops\nconsecutive",
    'POSIX_CONSEC_WRITES_PERC'        : "% W Ops\nconsecutive",
    'POSIX_FILE_NOT_ALIGNED_PERC'     : "File not\naligned %",
    'POSIX_MEM_NOT_ALIGNED_PERC'      : "Memory not\naligned%",
    'POSIX_SIZE_READ_0_100_PERC'      : "% R Ops in\n0-100 B",    
    'POSIX_SIZE_READ_100_1K_PERC'     : "% R Ops in\n100-1000 B",   
    'POSIX_SIZE_READ_1K_10K_PERC'     : "% R Ops in\n1-10 KiB",
    'POSIX_SIZE_READ_10K_100K_PERC'   : "% R Ops in\n10-100 KiB",
    'POSIX_SIZE_READ_100K_1M_PERC'    : "% R Ops in\n100-1000 KiB",
    'POSIX_SIZE_READ_1M_4M_PERC'      : "% R Ops in\n1-4 MiB",
    'POSIX_SIZE_READ_4M_10M_PERC'     : "% R Ops in\n4-10 MiB",
    'POSIX_SIZE_READ_10M_100M_PERC'   : "% R Ops in\n10-100 MiB",
    'POSIX_SIZE_READ_100M_1G_PERC'    : "% R Ops in\n100-1000 MiB", 
    'POSIX_SIZE_READ_1G_PLUS_PERC'    : "% R Ops in\n1 GiB and up", 
    'POSIX_SIZE_WRITE_0_100_PERC'     : "% W Ops in\n0-100 B",    
    'POSIX_SIZE_WRITE_100_1K_PERC'    : "% W Ops in\n100-1000 B",   
    'POSIX_SIZE_WRITE_1K_10K_PERC'    : "% W Ops in\n1-10 KiB",
    'POSIX_SIZE_WRITE_10K_100K_PERC'  : "% W Ops in\n10-100 KiB",
    'POSIX_SIZE_WRITE_100K_1M_PERC'   : "% W Ops in\n100-1000 KiB",
    'POSIX_SIZE_WRITE_1M_4M_PERC'     : "% W Ops in\n1-4 MiB",
    'POSIX_SIZE_WRITE_4M_10M_PERC'    : "% W Ops in\n4-10 MiB",
    'POSIX_SIZE_WRITE_10M_100M_PERC'  : "% W Ops in\n10-100 MiB",
    'POSIX_SIZE_WRITE_100M_1G_PERC'   : "% W Ops in\n100-1000 MiB", 
    'POSIX_SIZE_WRITE_1G_PLUS_PERC'   : "% W Ops in\n1 GiB and up", 
    'POSIX_ACCESS1_COUNT_PERC'        : "Access1\nbin %",
    'POSIX_ACCESS2_COUNT_PERC'        : "Access2\nbin %",
    'POSIX_ACCESS3_COUNT_PERC'        : "Access3\nbin %",
    'POSIX_ACCESS4_COUNT_PERC'        : "Access4\nbin %",
    'POSIX_LOG10_MODE'                : "POSIX mode",
    'POSIX_LOG10_total_bytes'         : "Data volume",
    'LOG10_nprocs'                    : "App size\n(nprocs)",
    'POSIX_LOG10_SEEKS'               : "Seeks #",
    'LOG10_runtime'                   : "Runtime",
    'POSIX_LOG10_STATS'               : "Stats #",
    'POSIX_LOG10_MMAPS'               : "Mmaps #",
    'POSIX_LOG10_FSYNCS'              : "Fsyncs #",
    'POSIX_LOG10_MEM_ALIGNMENT'       : "Mem\nalignment #",
    'POSIX_LOG10_FILE_ALIGNMENT'      : "File\nalignment #",
    'POSIX_LOG10_OPENS'               : "Opens #",
    'POSIX_LOG10_total_accesses'      : "Read+Write #",
    'POSIX_LOG10_total_files'         : "Files\naccessed #",
}

